#!/bin/sh

podman run --rm -d --name artemis \
         -p 61616:61616 \
         -p 8161:8161 \
         -p 5445:5445 \
         -p 5672:5672 \
         -p 1883:1883 \
         -p 61613:61613 \
         -v apache-artemis:/var/lib/artemis-instance \
         apache-artemis
